version: "3"

services:
  url-shortener:
    image: url-shortener:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - REDIS_ADDR=cache:6379
      - MONGO_ADDR=mongodb://database:27017
      - MODE=cached  # MODE: {in-memory, mongo, cached}
    depends_on:
      - database
      - cache
    
  database:
    image: mongo:4.4
    ports:
      - 27017:27017

  cache:
    image: redis:6.2.6
    ports:
      - 6379:6379
