openapi: 3.0.3
info:
  title: URL Shortener
  description: URL Shortener
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /api/urls:
    post:
      summary: Create a new short link for the given address
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [url]
              properties:
                url:
                  type: string
                  format: uri
                  nullable: false
      responses:
        200:
          description: Short link created successfully.
          content:
            application/json:
              schema:
                type: object
                required: [key]
                properties:
                  key:
                    type: string
                    description: The key by which you can get a redirect to a given URL.
                    pattern: '\w{5}'
                    nullable: false
  /{key}:
    parameters:
      - in: path
        name: key
        required: true
        description: The key that was obtained when creating a short link for the request `POST /api/urls`.
        schema:
          type: string
          pattern: '\w{5}'
    get:
      summary: Execute redirect
      responses:
        308:
          description: The requested resource has been moved.
          headers:
            Location:
              required: true
              description: The redirect address specified when setting the short link.
        404:
          description: This key is not a short link.